name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: 
      - opened
      - reopened
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Markdown files
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: books

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: [mondstadt,liyue,inazuma,sumeru,teyvat]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # wildcard * is not expanded in workflow cmd
      - name: Create files list
        id: flist
        run: >-
          echo
          "files=$(printf '"%s" ' books/${{ matrix.collection }}/*)"
          >> $GITHUB_OUTPUT

      - name: Build EPUB with pandoc
        uses: docker://pandoc/core:2.18
        with:
          args: >-
            -o genshin-books-${{ matrix.collection }}-${{ github.ref_name }}.epub
            books/foreword.md
            ${{ steps.flist.outputs.files }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.collection }}
          path: '*.epub'
          if-no-files-found: error

  release:
    needs: [build, lint]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        id: books
        with:
          path: books

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: '${{steps.books.outputs.download-path}}/**/*.epub'
          fail_on_unmatched_files: true
          generate_release_notes: true
