name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Markdown files
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: books
