name: Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Markdown files
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: books
